### ISSUE TITLE
Issues on Windows OS

### ISSUE THREAD

**Issue by VioletGiraffe** [alexcastano/borderless-qt#3]
I realize this is just a simple demo / example, but still feel like listing issues on Windows. I think they're all related to the fact that Aero features are disabled for borderless windows (see this [qt.io forum post](http://forum.qt.io/topic/56493/qtwidgets-is-it-possible-to-apply-flat-main-window-style-visual-studio-like-via-qss/5)).
- [ ] Window is minimized / maximized with no animation whatsoever
- [ ] Snap to screen edges / Win + cursor arrow hotkeys don't work

**Comment by VioletGiraffe** [comment]
Here's a borderless Qt Widgets window with Aero features (shadow, edge snap, animation): https://github.com/deimos1877/BorderlessWindow

**Comment by alexcastano** [comment]
This is a very old repo. I don't code anymore with Qt.
